import pytest
from decimal import Decimal
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.obra import Obra
from app.models.versao import Versao
from app.models.grupo import Grupo
from app.models.item import Item
from app.services.totais_service import recalc_totais_versao
from datetime import date


@pytest.mark.asyncio
async def test_recalc_totais_soma_itens(db_session: AsyncSession, empresa):
    obra = Obra(
        empresa_id=empresa.id, nome="Obra Teste", tipo_obra="rodovia",
        estado="em_elaboracao", data_criacao=date.today(),
    )
    db_session.add(obra)
    await db_session.flush()

    versao = Versao(obra_id=obra.id, numero=1)
    db_session.add(versao)
    await db_session.flush()

    grupo = Grupo(versao_id=versao.id, nome="Terraplenagem", ordem=0)
    db_session.add(grupo)
    await db_session.flush()

    # Insert items — total is GENERATED by PostgreSQL, never set it
    i1 = Item(
        grupo_id=grupo.id, ordem=0, quantidade=Decimal("100"),
        unidade="m3", preco_unitario_sem_bdi=Decimal("10.000000"),
        preco_unitario_com_bdi=Decimal("12.000000"),
    )
    i2 = Item(
        grupo_id=grupo.id, ordem=1, quantidade=Decimal("50"),
        unidade="m3", preco_unitario_sem_bdi=Decimal("20.000000"),
        preco_unitario_com_bdi=Decimal("24.000000"),
    )
    db_session.add_all([i1, i2])
    await db_session.flush()

    await recalc_totais_versao(versao.id, db_session)
    await db_session.refresh(versao)

    # total_sem_bdi = 100*10 + 50*20 = 2000
    assert versao.total_sem_bdi == Decimal("2000.00")
    # total_com_bdi = 100*12 + 50*24 = 2400
    assert versao.total_com_bdi == Decimal("2400.00")


@pytest.mark.asyncio
async def test_recalc_totais_sem_itens(db_session: AsyncSession, empresa):
    obra = Obra(
        empresa_id=empresa.id, nome="Obra Vazia", tipo_obra="outro",
        estado="em_elaboracao", data_criacao=date.today(),
    )
    db_session.add(obra)
    await db_session.flush()

    versao = Versao(obra_id=obra.id, numero=1)
    db_session.add(versao)
    await db_session.flush()

    await recalc_totais_versao(versao.id, db_session)
    await db_session.refresh(versao)

    assert versao.total_sem_bdi == Decimal("0")
    assert versao.total_com_bdi == Decimal("0")
